# 통계기반 자연어 처리

##  NLP의 접근 방식
1. 규칙 시반
    - 사람의 규칙(문법/패턴)을 정의
2. 통계 기반
    - 단어의 빈도, 확률, 통계를 활용
3. 딥러닝 기반
    - 대규모 데이터 + 신경망 모델 활용

## N-gram 근사
- Unigram
    - N = 1
    - 독립 단어 (하나의 단어)
- bigram
    - N = 2
    - 바로 앞의 단어를 고려
- trigram
    - N = 3
    - 앞의 2개의 단어를 고려

## 로그 확률
- 단어의 조건부 확률은 매우 작은 값 (0.0001, 0.00001)
- 조건부의 확률들끼리 곱하게 되면 -> 0에 가까운 값 -> 계산이 불안정해짐
- 이러한 문제를 해결하기 위해 log 값을 사용

## 혼란도(Perplexity)
- 문장을 얼마나 헷갈려하는지를 수치로 표현한 값
- 값이 높다면 -> 문장 이해도가 내려간다.
- 값이 낮다면 -> 문장 이해도가 올라간다.

### BoW 
- 문서의 단어 순서는 무시
- 각 문서에서 단어가 몇번 등장했는가? (빈도수)
- 가장 기본적인 백터화 방법

In [3]:
# 샘플 데이터셋 생성
docs = [
    "영화가 정말 재미있었다",
    "영화가 너무 지루하다",
    "배우의 연기가 너무 좋았다",
]

In [4]:
tokens = [doc.split() for doc in docs]
tokens

[['영화가', '정말', '재미있었다'], ['영화가', '너무', '지루하다'], ['배우의', '연기가', '너무', '좋았다']]

In [5]:
# tokens에서 각각의 단어들을 하나의 리스트로 생성하고 중복은 제거
# tokens의 2차원 리스트를 1차원으로 변환
vocab1 = []
for token in tokens:
    # token -> tokens의 각 원소들 -> 1차원 리스트
    for word in token:
        # word : token이라는 1차원 리스트의 각각의 원소들
        vocab1.append(word)
        
vocab1 = list(set(vocab1))

In [6]:
vocab1

['정말', '재미있었다', '너무', '지루하다', '좋았다', '연기가', '영화가', '배우의']

In [7]:
vocab = list(set(sum(tokens, [])))

In [8]:
# BoW 행렬을 하나 생성
# tokens의 문장에 vocab의 단어가 몇개 포함되어있는가?
bow_list = []
vocab.sort()
for doc in tokens:
    #row = [doc.count(word) for word in vocab]
    row = []
    for word in vocab:
        # count() 함수는 list에서 인자의 값과 같은 데이터가 몇개 있는가?
        row.append(doc.count(word))
    bow_list.append(row)

In [9]:
import pandas as pd

In [10]:
df_bow = pd.DataFrame(bow_list, columns=vocab)

In [11]:
df_bow

   너무  배우의  연기가  영화가  재미있었다  정말  좋았다  지루하다
0   0    0    0    1      1   1    0     0
1   1    0    0    1      0   0    0     1
2   1    1    1    0      0   0    1     0

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(docs)

In [14]:
df_vectorizer = pd.DataFrame(X.toarray(),
                            columns=vectorizer.get_feature_names_out())

In [15]:
df_vectorizer

   너무  배우의  연기가  영화가  재미있었다  정말  좋았다  지루하다
0   0    0    0    1      1   1    0     0
1   1    0    0    1      0   0    0     1
2   1    1    1    0      0   0    1     0

### TF-TDF
- Bow 모델(단순 빈도 모델)의 한계를 보완하기 위한 통계 기반 기법

- TF
    - 문서 내의 빈도가 높을수록 값이 큼
    - 자주 등장할수록 그 문서에서 중요하다고 판단
- IDF
    - 문장 내에서의 단어의 희소성

In [16]:
import math

In [17]:
# 전체 문서의 길이
N = len(docs)

In [18]:
# 단어의 개수를 생성
word_cnt = {
    w : sum(1 for doc in tokens if w in doc) for w in vocab
}
word_cnt

{'너무': 2,
 '배우의': 1,
 '연기가': 1,
 '영화가': 2,
 '재미있었다': 1,
 '정말': 1,
 '좋았다': 1,
 '지루하다': 1}

In [19]:
# TF 계산식 함수
def tf(word, doc):
    # word : 단어 사전의 각 원소
    # doc : tokens 각 원소
    # doc.count(Word) : 문장에서 특정 단어의 개수
    # len(doc) : 문장의 단어의 개수
    result = doc.count(word) / len(doc)
    return result

In [20]:
# IDF 계산식 함수
def idf(word):
    # word : 단어 사전의 각 원소
    # N : docs의 길이 -> 문장들의 개수
    # word_cnt[word] -> 문서에서 특정 단어의 개수
    result = math.log((N) / (word_cnt[word] + 1)) + 1
    return result

In [21]:
# TF-IDF -> TF의 값과 IDF 값을 곱한 수치
X_tfidf = [
    [tf(w, doc) * idf(w) for w in vocab] for doc in tokens
]
X_tfidf

[[0.0,
  0.0,
  0.0,
  0.3333333333333333,
  0.4684883693693881,
  0.4684883693693881,
  0.0,
  0.0],
 [0.3333333333333333,
  0.0,
  0.0,
  0.3333333333333333,
  0.0,
  0.0,
  0.0,
  0.4684883693693881],
 [0.25,
  0.3513662770270411,
  0.3513662770270411,
  0.0,
  0.0,
  0.0,
  0.3513662770270411,
  0.0]]

In [22]:
pd.DataFrame(X_tfidf, columns=vocab)

,너무,배우의,연기가,영화가,재미있었다,정말,좋았다,지루하다
0,0.000000,0.000000,0.000000,0.333333,0.468488,0.468488,0.000000,0.000000
1,0.333333,0.000000,0.000000,0.333333,0.000000,0.000000,0.000000,0.468488
2,0.250000,0.351366,0.351366,0.000000,0.000000,0.000000,0.351366,0.000000

In [23]:
# TF-IDF는 scikit-learn에 class가 존재
from sklearn.feature_extraction.text import TfidfVectorizer

In [24]:
vector = TfidfVectorizer(
    ngram_range=(1, 1),
    min_df=1
)
X = vector.fit_transform(docs)
pd.DataFrame(
    X.toarray(),
    columns=vector.get_feature_names_out()
)

,너무,배우의,연기가,영화가,재미있었다,정말,좋았다,지루하다
0,0.000000,0.000000,0.000000,0.473630,0.622766,0.622766,0.000000,0.000000
1,0.517856,0.000000,0.000000,0.517856,0.000000,0.000000,0.000000,0.680919
2,0.402040,0.528635,0.528635,0.000000,0.000000,0.000000,0.528635,0.000000

- 감정 분석에서 TF-IDF + SVM의 조합이 보편적으로 사용
    - 단어별로 feature가 생성이 되기 때문에 고차원 데이터가 생성이 되고 value가 0인 데이터가 많은 비율을 차지 하기 때문에 트리구조를 중복으로 사용하는 배깅 부스팅은 어울리지 않는다.
- ngram_range는 (1, 2)로 사용을 하게 되면 '너무 좋았다', '정말 별로다' 이러한 단어 패턴도 포착 가능
- 고차원으로 생성이 된 행렬 데이터를 차원 축소 기법을 이용하여 차원의 수를 모델에 학습하여 성능을 평가하는 방법도 존재

### N-gram
- 단어를 몇 개까지 하나로 불 것인가?
- 언어의 모델을 문장의 자연스러움으로 수치화하는 통계적 방법
- 수치화 값으로는 로그확률, 혼란도
- 로그확률은 매우 크지 않은 음수인 경우 자연스러움 표현 
- 혼란도 낮을수록 자연스러움을 표현

In [25]:
# 샘플 데이터를 생성
texts = [
    '오늘 날씨가 좋다',
    '오늘 기분이 좋다',
    '내일 날씨가 맑다',
    '기분이 아주 좋다',
    '날씨가 아주 좋다'
]

In [26]:
from konlpy.tag import Okt

In [27]:
# 토큰화 함수 생성
okt = Okt()
def tokenize(text):
    result = okt.morphs(text)
    return result

In [28]:
# 문장의 시작과 끝 부분에 태그를 추가
tokens = [['<s>'] + tokenize(text) + ['</s>'] for text in texts]
tokens

[['<s>', '오늘', '날씨', '가', '좋다', '</s>'],
 ['<s>', '오늘', '기분', '이', '좋다', '</s>'],
 ['<s>', '내일', '날씨', '가', '맑다', '</s>'],
 ['<s>', '기분', '이', '아주', '좋다', '</s>'],
 ['<s>', '날씨', '가', '아주', '좋다', '</s>']]

In [29]:
# unigram, bigram 카운트 화인
from collections import Counter
unigram = Counter(w for token in tokens for w in token)
bigram = Counter((token[i], token[i+1])for token in tokens for i in range(len(token) - 1))

print(unigram)
print(bigram)

Counter({'<s>': 5, '</s>': 5, '좋다': 4, '날씨': 3, '가': 3, '오늘': 2, '기분': 2, '이': 2, '아주': 2, '내일': 1, '맑다': 1})
Counter({('좋다', '</s>'): 4, ('날씨', '가'): 3, ('<s>', '오늘'): 2, ('기분', '이'): 2, ('아주', '좋다'): 2, ('오늘', '날씨'): 1, ('가', '좋다'): 1, ('오늘', '기분'): 1, ('이', '좋다'): 1, ('<s>', '내일'): 1, ('내일', '날씨'): 1, ('가', '맑다'): 1, ('맑다', '</s>'): 1, ('<s>', '기분'): 1, ('이', '아주'): 1, ('<s>', '날씨'): 1, ('가', '아주'): 1})

In [30]:
# 다중 for문을 풀어서 작성
# for token in tokens:
#     for i in range(len(token) - 1):
#         print(token[i], token[i+1])

In [31]:
# 문서 내에서 단어의 개수
V = len(unigram)
print(V)

11

In [32]:
# 확률이 0이 나오는 경우
# Add-1 smoothing(Laplace Smoothing)
# 분자에 +1 -> 분모에는 + 문장에서의 단어의 개수
def bigram_prob(prev, curr):
    # bigram[(prev, curr)] -> 연결된 두개의 단어의 개수
    # unigram[prev] -> 앞의 단어의 개수
    # 특정 단어 뒤에 단어가 나올 확률
    result = (bigram[(prev, curr)] + 1) / (unigram[prev] + V)
    return result

# 로그 확률 -> 음수의 절대값이 크지 않다면 자연스러운 구조
def log_prob(text):
    # tokens : 문자을 토큰화한 리스트
    # 문장의 시작과 끝에 태그 추가
    seq = ['<s>'] + text + ['</s>']
    # 로그 확률의 누적합을 위해 초기 값 0.0지정
    log_p = 0.0
    for i in range(len(seq) - 1):
        # 확률 생성
        p = bigram_prob(seq[i], seq[i+1])
        # log_p에 누적합
        log_p += math.log(p)
    return log_p

In [33]:
# 혼란도
def perplexity(tokens):
    # tokens : 문장을 토큰화한 리스트
    log_p = log_prob(tokens)
    T = len(tokens) + 1
    # 자연상수 계산식
    result = math.exp(-log_p / T)
    return result

In [34]:
# 학습된 unigram / bigram을 이용하여 확률을 계산하고 로그 확률, 혼란도 확인
new_texts = [
    '오늘 날씨가 말다',
    '기분이 내일 좋다',
    '날씨가 아주 좋다'
]

result = []
for text in new_texts:
    tokens = tokenize(text)
    # 로그확률
    lp = log_prob(tokens)
    # 혼란도
    perple = perplexity(tokens)
    result.append([text, lp, perple])

In [35]:
pd.DataFrame(result, columns= ['문장', '로그확률', '혼란도'])

          문장      로그확률       혼란도
0  오늘 날씨가 말다 -9.835494  7.149903
1  기분이 내일 좋다 -9.694247  6.950749
2  날씨가 아주 좋다 -7.843064  4.799985

## 실습 문제
- rating_test.txt 파일을 로드
- document 컬럼의 결측치를 제외하고 list 형태로 변환(데이터의 개수는 상위 5000개만)
- unigram, bigram 단어의 개수를 생성
- 로그확률, 혼란도 함수를 생성
- new_texts를 이용하여 로그확률, 혼란도를 생성

In [60]:
df = pd.read_csv('../data/ratings_test.txt', sep='\t')

In [61]:
df.dropna(inplace=True)
doc = df['document'].tolist()[:5000]

In [62]:
tokens = [['<s>'] + tokenize(text) + ['</s>'] for text in doc]
tokens

[['<s>', '굳', 'ㅋ', '</s>'],
 ['<s>', 'GDNTOPCLASSINTHECLUB', '</s>'],
 ['<s>',
  '뭐',
  '야',
  '이',
  '평점',
  '들',
  '은',
  '....',
  '나쁘진',
  '않지만',
  '10',
  '점',
  '짜',
  '리',
  '는',
  '더',
  '더욱',
  '아니잖아',
  '</s>'],
 ['<s>',
  '지루하지는',
  '않은데',
  '완전',
  '막장',
  '임',
  '...',
  '돈',
  '주고',
  '보기',
  '에는',
  '....',
  '</s>'],
 ['<s>',
  '3',
  'D',
  '만',
  '아니었어도',
  '별',
  '다섯',
  '개',
  '줬을텐데',
  '..',
  '왜',
  '3',
  'D',
  '로',
  '나와서',
  '제',
  '심기',
  '를',
  '불편하게',
  '하죠',
  '??',
  '</s>'],
 ['<s>', '음악', '이', '주가', '된', ',', '최고', '의', '음악', '영화', '</s>'],
 ['<s>', '진정한', '쓰레기', '</s>'],
 ['<s>',
  '마치',
  '미국',
  '애니',
  '에서',
  '튀어나온듯',
  '한',
  '창의력',
  '없는',
  '로봇',
  '디자인',
  '부터가',
  ',',
  '고개',
  '를',
  '젖게',
  '한다',
  '</s>'],
 ['<s>',
  '갈수록',
  '개판',
  '되가는',
  '중국영화',
  '유치하고',
  '내용',
  '없음',
  '폼',
  '잡다',
  '끝남',
  '말',
  '도',
  '안되는',
  '무기',
  '에',
  '유치한',
  'cg',
  '남무',
  '아',
  '그립다',
  '동사서독',
  '같은',
  '영화',
  '가',
  '이건',
  '3',
  '류',
  '아',
  '류작',
  '이다',
  '</s>'],
 ['<s>',
  '이별',
  '의',
  '아픔',
  '뒤',
  '에',
  '찾아오는',
  '새로운',
  '인연',
  '의',
  '기쁨',
  'But',
  ',',
  '모든',
  '사람',
  '이',
  '그렇지는',
  '않네',
  '..',
  '</s>'],
 ['<s>', '괜찮네요', '오랜', '만', '포켓몬스터', '잼밌', '어', '요', '</s>'],
 ['<s>', '한국', '독립영화', '의', '한계', '그렇게', '아버지', '가', '된다와', '비교', '됨', '</s>'],
 ['<s>',
  '청춘',
  '은',
  '아름답다',
  '그',
  '아름다',
  '움',
  '은',
  '이성',
  '을',
  '흔들어',
  '놓는다',
  '.',
  '찰나',
  '의',
  '아름다',
  '움',
  '을',
  '잘',
  '포착',
  '한',
  '섬세하고',
  '아름다운',
  '수채화',
  '같은',
  '퀴어',
  '영화',
  '이다',
  '.',
  '</s>'],
 ['<s>',
  '눈',
  '에',
  '보이는',
  '반전',
  '이었지만',
  '영화',
  '의',
  '흡인',
  '력',
  '은',
  '사라지지',
  '않았다',
  '.',
  '</s>'],
 ['<s>',
  '"',
  '스토리',
  ',',
  '연출',
  ',',
  '연기',
  ',',
  '비주',
  '얼',
  '등',
  '영화',
  '의',
  '기본',
  '조차',
  '안된',
  '영화',
  '에',
  '무슨',
  '평',
  '을',
  '해',
  '.',
  '이런',
  '영화',
  '찍고도',
  '김문옥',
  '감독',
  '은',
  '""',
  '내',
  '가',
  '영화',
  '경력',
  '이',
  '몇',
  'OO',
  '인데',
  '조무래기',
  '들',
  '이',
  '내',
  '영화',
  '를',
  '평론',
  '해',
  '?""',
  '같은',
  '마인드',
  '에',
  '빠져있겠지',
  '?"',
  '</s>'],
 ['<s>', '소위', 'ㅈ', '문', '가라', '는', '평점', '은', '뭐', '냐', '?', '</s>'],
 ['<s>', '최고', '!!!!!!!!!!!!!!!!', '</s>'],
 ['<s>',
  '발연기',
  '도저히',
  '못',
  '보겠다',
  '진짜',
  '이렇게',
  '연기',
  '를',
  '못',
  '할거라곤',
  '상상',
  '도',
  '못',
  '했네',
  '</s>'],
 ['<s>', '나이스', '</s>'],
 ['<s>',
  '별',
  '재미',
  '도',
  '없는거',
  '우려',
  '먹어',
  '....',
  '챔프',
  '에서',
  '방송',
  '몇번',
  '했더라',
  '?',
  'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',
  '</s>'],
 ['<s>',
  "'",
  '13일',
  '의',
  '금요일',
  "',",
  "'",
  '나이트메어',
  "'",
  '시리즈',
  '와',
  '함께',
  '가장',
  '많은',
  '시리즈',
  '를',
  '양산',
  '해냈던',
  '헬레',
  '이',
  '저',
  '시리즈',
  '의',
  '첫',
  '편',
  '.',
  '작가',
  '의',
  '상상력',
  '이',
  '돋보이는',
  '작품',
  '이며',
  ',',
  '갈고리',
  '로',
  '사지',
  '찢는',
  '고어씬',
  '은',
  '지금',
  '보더',
  '라도',
  '상당히',
  '잔인하고',
  '충격',
  '적',
  '이다',
  '.',
  '</s>'],
 ['<s>',
  '나름',
  '교훈',
  '돋기는',
  '하지만',
  '어쩔',
  '수없이',
  '저',
  '평점',
  '받을수밖에',
  '없는',
  '저',
  '질',
  '섹스',
  '코미디',
  '</s>'],
 ['<s>', '꽤', '재밌게', '본', '영화', '였다', '!', '</s>'],
 ['<s>',
  '민주화',
  '시대',
  '의',
  '억눌린',
  '영혼',
  '의',
  '관음',
  '적',
  '인',
  '욕구',
  '분출',
  '.',
  '인상',
  '적',
  '이다',
  '.',
  '</s>'],
 ['<s>',
  '일본',
  '천황',
  '이',
  '미국',
  '으로부터',
  '받은',
  '면죄부',
  '의',
  '긴박한',
  '과정',
  '을',
  '루즈',
  '하고',
  '지저분하게',
  '늘어놓았다',
  '.',
  '</s>'],
 ['<s>',
  '괜히',
  '나올',
  '때',
  '어미',
  '알',
  '건드려서',
  '긁어',
  '부스',
  '름',
  '만들었다는',
  '분',
  '이',
  '저',
  '아래',
  '보이던데',
  ',',
  '영화',
  '제대로',
  '안',
  '봤네',
  '.',
  '알',
  '이',
  '딱',
  '까지면서',
  '새끼',
  '가',
  '나오려',
  '했음',
  '.',
  '그냥',
  '가면',
  '그',
  '놈',
  '한테',
  '당했을',
  '것임',
  '.',
  '한',
  '놈',
  ',',
  '두',
  '놈',
  '막',
  '나올',
  '게',
  '뻔했으니',
  '작살',
  '낼',
  '수',
  '밖에',
  '없었다',
  '.',
  '</s>'],
 ['<s>', '50', '번은', '봤네요', '어쩜', '이렇게', '잘', '만들었을까', '</s>'],
 ['<s>',
  '실화',
  '라서',
  '더욱',
  '아름답고',
  '찡하네요',
  '...',
  '많이',
  '울었어요',
  '벌써',
  '4년',
  '이란시간이흘렀네요',
  '</s>'],
 ['<s>',
  '이건',
  '뭐',
  '노답',
  '이네',
  '80~90년',
  '대',
  '어린이',
  '영화',
  '좀',
  '보고',
  '본받아라',
  '!',
  '</s>'],
 ['<s>',
  '지금',
  '까지',
  '본',
  '영화',
  '중',
  '마음',
  '이',
  '가장',
  '따뜻해지는',
  '영화',
  '.',
  '</s>'],
 ['<s>', '너무', '너무', '재밌다', '</s>'],
 ['<s>', '안보', '면', '후회', 'ㅠㅠ', '...', '</s>'],
 ['<s>',
  '평점',
  '1',
  '점도',
  '주기',
  '싫어지는',
  '영화',
  '배우',
  '나',
  '감독',
  '이라는',
  '사람',
  '이나',
  '영',
  '화판',
  '에서',
  '안',
  '봐으면',
  '한다',
  '그리고',
  '평점',
  '알바생',
  '들',
  '너무',
  '티',
  '난다',
  '</s>'],
 ['<s>', '정말', ',', '진짜', ',', '표현', '할수', '없는', '영화', '...', '</s>'],
 ['<s>',
  '엉',
  '성한',
  '액션',
  '에',
  ',',
  '시나리오',
  '는',
  '왜그러지',
  '..',
  '막판',
  '에',
  '대동단결',
  '??',
  '</s>'],
 ['<s>', '101', ',', '102', '..', '103', '은', '못', '나올것', '같다', '.', '</s>'],
 ['<s>', '....', '재미', '가', '없어요', '시간', '이', '아깝고', '</s>'],
 ['<s>', '북괴', '는', '우리', '의', '주적', '일', '뿐', '이다', '.', '</s>'],
 ['<s>',
  'ㅋㅋㅋ',
  '난생처음',
  '로그인',
  '하고',
  '평점',
  '남기네요',
  '..',
  '개',
  '빡쳐서',
  '..',
  '알바',
  '들',
  '속지',
  '마세요',
  '이런',
  'ㄱ',
  'ㅐ',
  '같은',
  '시간',
  '낭비',
  '가',
  '.',
  '아',
  '놔',
  '진짜',
  '평점',
  '마이너스',
  '별',
  '오만',
  '개',
  '</s>'],
 ['<s>', '셰익스피어', '는', '셰익스피어', '고', '이영화', '는', '이영화', '.', '</s>'],
 ['<s>',
  'EBS',
  '한국영',
  '화',
  '특선',
  '해서',
  '봤다',
  '.',
  'Biff',
  '개막',
  '작',
  '선정',
  '되서',
  '왤까',
  '궁금',
  '했었는데',
  '봐도',
  '이율',
  '모르겠다',
  '...',
  '</s>'],
 ['<s>', '뭐', '야', '??', '라는', '말', '밖에는', '...', '</s>'],
 ['<s>', '이', '게', '영화', '야', '?', '</s>'],
 ['<s>', '애니', '는', '일본', '이', '갑인듯', '.', '</s>'],
 ['<s>', '롭', '코헨', '의', '몰락', '의', 'OO', '점', '</s>'],
 ['<s>', '감동', '적', '이다', '....', '</s>'],
 ['<s>', '은빛', '날개', '의', '조종사', '</s>'],
 ['<s>',
  '마음',
  '이',
  '1',
  '을',
  '보신',
  '분들',
  '은',
  '이해',
  '하시겟지만',
  '2',
  '는',
  '망',
  '장',
  '입니다',
  '졸작',
  '이',
  '죠',
  '솔직히말해',
  '선',
  ';;',
  '그',
  '이유',
  '는',
  '예',
  '를',
  '들',
  '면',
  '엽기적인그녀',
  '는',
  '긴',
  '시간',
  '을',
  '두고',
  '코',
  '메디',
  '멜로',
  '를',
  '그',
  '렷습',
  '니',
  '다',
  '하지만',
  '이영화',
  '는',
  '단시간',
  '10분',
  '안에',
  '모든',
  '것',
  '을',
  '소화',
  '하려는',
  '욕심',
  '코믹',
  '하다',
  '3분',
  '채안돼갑자기',
  '생뚱맞',
  '게',
  '슬픈',
  '음악',
  '이',
  '깔리고',
  '</s>'],
 ['<s>', '이런', '스타일', '액션영화', '굿굿', '!!', '</s>'],
 ['<s>', '제임스', '헷', '필드', '50', '먹고', '더', '파워', '풀해', '졌어', 'ㅋㅋㅋㅋ', '</s>'],
 ['<s>',
  '돈',
  '만',
  '있으면',
  '내',
  '가',
  '이',
  '것',
  '보단',
  '더잘',
  '만들겠',
  '따',
  'ㅋ',
  '</s>'],
 ['<s>', '레이토', '와', '다미앙', '의', '시원한', '액션', '은', '어디', '갔나', 'ㅁㅊ', '</s>'],
 ['<s>',
  '내',
  '참',
  ',',
  '이딴',
  '걸',
  '드라마',
  '라고',
  '....',
  '그냥',
  '이건',
  '세계보건기구',
  '에서',
  '발암',
  '물질',
  '로',
  '올려야',
  '한다',
  '.',
  '</s>'],
 ['<s>',
  '아',
  '극장',
  '에서',
  '아무',
  '기대',
  '없이',
  '들어갔다가',
  '감탄',
  '하면서',
  '보고',
  '나왔는데',
  '.',
  '2001년',
  '도',
  '였구나',
  '그',
  '때',
  '가',
  '.',
  '</s>'],
 ['<s>', '아이디어', '가', '아주', '좋다', '재밌다', '</s>'],
 ['<s>', '난', '재밌던데', '평점', '왜케', '낮지', '``;', '</s>'],
 ['<s>',
  '역사',
  '얘기',
  '보다',
  '영화배우',
  ',',
  '감독',
  '들',
  '들에게',
  '더',
  '관심',
  '이',
  '간다',
  '</s>'],
 ['<s>',
  '몇',
  '년',
  '만에',
  '아메리칸',
  '조',
  '크보',
  '고',
  '웃어',
  '보는거지',
  '.',
  '하아',
  '이',
  '맛',
  '이야',
  '바로',
  '</s>'],
 ['<s>',
  '재밌다',
  '!',
  '내용',
  '도',
  '신선하고',
  '의미',
  '도',
  '있으며',
  '연기',
  '도',
  '좋고',
  '영상',
  '도',
  '좋다',
  '~~',
  '</s>'],
 ['<s>', '여름', '이면', '한결같이', '생각나는', '드라마', '</s>'],
 ['<s>', '콩콩', '~~~~', 'ㅋㄲㅈㅁ', '</s>'],
 ['<s>',
  '...',
  '으',
  '...',
  '뭐',
  '의도',
  '는',
  '좋아',
  '봤자',
  '전달',
  '이',
  '돼야지',
  ';',
  '</s>'],
 ['<s>', '아빠', '가', '낚', '여서', '본적', '있다나', '슈래기', '영화', '</s>'],
 ['<s>',
  '"""',
  '결혼',
  '은',
  '현실',
  '이에요',
  '징징',
  '징',
  '""',
  '성현아',
  '벗겨놓고',
  '이',
  '정도',
  '얘기',
  '밖에',
  '못',
  '하냐',
  '."',
  '</s>'],
 ['<s>',
  '엠비씨',
  '무비',
  '채널',
  '에서',
  '봤는데',
  '또',
  '봐도',
  '엄청',
  '잼',
  '나네여',
  '..',
  '</s>'],
 ['<s>',
  '어우',
  '..',
  '이',
  '게',
  '진짜',
  '무서웠어요',
  '??',
  '진짜',
  '로',
  '?',
  '시간',
  '아까웠습니다',
  '.',
  '</s>'],
 ['<s>', '몇번', '을', '봐도', '볼때', '마다', '재밌다', '</s>'],
 ['<s>',
  '재미있게',
  '잘',
  '봤습니다',
  '후',
  '속편',
  '을',
  '기다리게',
  '만',
  '드',
  '네',
  '요',
  '</s>'],
 ['<s>', '결말', '뻔히', '알면서', '보는데도', '너무', '슬프고', '많이', '울었음', '.', '</s>'],
 ['<s>', '한번', '본적', '은', '업', '지만', '재미있을것', '같다', '</s>'],
 ['<s>',
  '성경',
  '에',
  '보면',
  '지나치게',
  '의인',
  '도',
  '되지',
  '말고',
  '지혜롭',
  '게',
  '되지도',
  '말',
  '라고',
  '했다',
  '.',
  '주인공',
  '의',
  '지나친',
  '착한',
  '남자',
  '컴플렉스',
  '는',
  '결국',
  '모든',
  '걸',
  '엉망',
  '으로',
  '만들었다',
  '.',
  '직장',
  '에서',
  '해고',
  '되고',
  '부인',
  '에게',
  '거부',
  '당',
  '하고',
  ',',
  '그',
  '모든',
  '터전',
  '을',
  '잃을만큼',
  '불륜',
  '으로',
  '생긴',
  '아이',
  '를',
  '보러가는게',
  '그리',
  '중요했을까',
  '???',
  '</s>'],
 ['<s>',
  '미친',
  '놈',
  '들',
  '집합소',
  '네',
  '연출',
  '력',
  '빵점',
  ',',
  '스토리',
  '빵점',
  '.',
  '구성',
  '빵점',
  '</s>'],
 ['<s>',
  '하',
  '...',
  '작은',
  '그림',
  '보고',
  '기대했는데',
  '..',
  '수염',
  '..',
  '눈',
  '색깔',
  '도',
  '뭐',
  '..',
  '이건',
  '뭐',
  '원작',
  '비',
  '충실',
  '..',
  'ㄹㄹ',
  '</s>'],
 ['<s>', '볼', '거', '없을', '때', '봐도', '재미', '없는', '영화', '!', '</s>'],
 ['<s>', '관객모독', '관객모독', '관객모독', '관객모독', '</s>'],
 ['<s>', '이런', '내용', '완전', '좋다', 'ㅠㅜㅜㅜ', '</s>'],
 ['<s>', '쇼타', '군', '넘', '좋아', '돈키호테', '대박', '재밌음', '</s>'],
 ['<s>', '참', '대단한것', '같습니다', '천', '...', '재', '..?', '</s>'],
 ['<s>', '볼', '만', '함', '</s>'],
 ['<s>', '제시카', '알바', '가', '벗고', '달려드는데', '쌩까는게', '말', '이', '되냐', '?', '</s>'],
 ['<s>',
  '솔직히',
  '이건',
  'C',
  '급',
  '그',
  '이하',
  '의',
  '영화',
  '이긴',
  '함',
  'ㅎㅎ',
  ';',
  '</s>'],
 ['<s>',
  '개성',
  '있는',
  '몬스터',
  '들',
  '과',
  '귀여운',
  '여자아이',
  '가',
  '만나',
  '뿜어내는',
  '매력',
  '에',
  '퐁당',
  '빠졌다',
  '</s>'],
 ['<s>', '제목', '이', '찰지구나', 'ㅋㅋㅋ', '</s>'],
 ['<s>',
  '1956년',
  '작품',
  '이라는',
  '게',
  '믿기지가',
  '않을',
  '정도',
  '로',
  '디테',
  '일하다',
  '!',
  '안소니',
  '퀸',
  '의',
  '명연기',
  '또한',
  '물론',
  '~',
  '</s>'],
 ['<s>', '아찔한', '사랑', '줄다리기', '???', '</s>'],
 ['<s>', '재미있었다', '!', '또', '봐야', '징', 'ㅎ', '</s>'],
 ['<s>', '중간', '에', '화면', '이', '좀', '끊기는것', '빼곤', '넘', '좋았어요', '~', '</s>'],
 ['<s>',
  '이',
  '영화',
  '를',
  '말',
  '하는데',
  '긴',
  '단어',
  '는',
  '필요없다',
  '.',
  '재수없는',
  '졸작',
  '이',
  '거',
  '면',
  '충분하다',
  '.',
  '</s>'],
 ['<s>',
  '최고',
  '최고',
  '!',
  '바다',
  '까지',
  '!',
  '4',
  '차원',
  '고양이',
  '로봇',
  '도라에몽',
  '과',
  '함께',
  '하는',
  '진구',
  '와',
  '친구',
  '들',
  '의',
  '미지',
  '탐험',
  '이야기',
  '!',
  '우주',
  '꺼',
  '지',
  '갔음',
  '좋겠당',
  '~',
  '</s>'],
 ['<s>', '완전', '잼', '없음', '..', '</s>'],
 ['<s>',
  '로코',
  '굉장히',
  '즐겨',
  '보는데',
  ',',
  '이',
  '영화',
  '는',
  '좀',
  '별로',
  '였다',
  '.',
  '뭔가',
  '사랑',
  '도',
  '개그',
  '도',
  '억지스런',
  '느낌',
  '..',
  '</s>'],
 ['<s>', '후속작', '계획', '은', '없나요', '..?', 'ㅜ', '</s>'],
 ['<s>', '엔딩', '때', '까지', '음성', '넣은', '것', '은', '오버', '의', '극치', '다', '</s>'],
 ['<s>', '단', '두', '마디', "'", '감동', "'", '</s>'],
 ['<s>', '뭘', '만든', '건가', '?', '</s>'],
 ['<s>', '전기톱', '은', '못', '들고다니는데', '엔진', '톱', '이', '겠죠', '</s>'],
 ['<s>', '완전', '재밌', '엇', '는데', '왜', '평점', '이', '??', '</s>'],
 ['<s>', '제임스', '완', '이', '내', '목표', '임', 'ㄷ', '</s>'],
 ['<s>',
  '1',
  '점',
  '고',
  '아깝다',
  '.',
  '개막',
  '장',
  '영화',
  '의',
  '원조',
  '라고',
  '나',
  '할까',
  '.',
  '아내',
  '와',
  '사별',
  '한',
  '지',
  '얼마나',
  '지났다고',
  '딴',
  '여자',
  '들',
  '만나고',
  '다니다가',
  '결국',
  '맥',
  '라이언',
  '한테',
  '꽂힌',
  '톰',
  '행크스',
  '나',
  '약혼자',
  '두고',
  '톰',
  '행크스',
  '랑',
  '썸',
  '타',
  '다가',
  '결국',
  '엔',
  '약혼자',
  '버리고',
  '톰',
  '행크스',
  '한테',
  '쪼르르',
  '달려가는',
  '맥',
  '라이언',
  '이나',
  '.',
  '</s>'],
 ['<s>',
  '가끔',
  '문득',
  '생각나서',
  '다시',
  '보는',
  '영화',
  '..',
  '색감',
  '이',
  '정말',
  '예술',
  '이',
  '죠',
  '강렬하고',
  '화려하고',
  '..',
  '츠지',
  '야',
  '안나',
  '의',
  '너무도',
  '아름답던',
  '리즈시절',
  '도',
  '볼',
  '수',
  '있고',
  '..',
  '</s>'],
 ['<s>', '걸작', '은', '몇', '안되고', '졸작', '들', '만', '넘쳐', '난다', '.', '</s>'],
 ['<s>', '이렇게', '지겨울수가', '</s>'],
 ['<s>',
  'ost',
  '...',
  '정말',
  '좋았어요',
  '.',
  '영화',
  '자체',
  '도',
  '..',
  '의문',
  '은',
  '남지',
  '만',
  'ㅎㅎ',
  '</s>'],
 ['<s>',
  '펑퍼짐한',
  '건빵',
  '바지',
  '(',
  '카',
  '고',
  ')',
  '를',
  '입고',
  '오도바이',
  '탈때',
  '입는',
  '잠바',
  '같은',
  '것',
  '을',
  '입은',
  '주인',
  '공겸',
  '감독',
  '이',
  '앞',
  '차기',
  '옆',
  '차기',
  '뒷',
  '차기',
  '앞',
  '돌려차기',
  '등',
  '의',
  '기술',
  '을',
  '구사해',
  '악당',
  '을',
  '소탕',
  '하는',
  '영화',
  '주먹질',
  '도',
  '하지만',
  '앞',
  '차기',
  '와',
  '옆',
  '차기',
  '의',
  '비중',
  '이',
  '크다',
  '</s>'],
 ['<s>',
  '솔직히',
  '생각',
  '보다',
  '재밌어서',
  '놀랐다',
  '...',
  '이',
  '거',
  '개봉',
  '하고',
  '낸',
  '린줄',
  '도',
  '모르고',
  '...',
  'ㅠ',
  'ㅠ',
  '이제',
  '서야',
  '봤네',
  '...',
  '정말',
  '두',
  '사람',
  '의',
  '커플',
  '댄스',
  '는',
  '...',
  '명',
  '장면',
  '이다',
  '...',
  '생각',
  '할수록',
  '아쉽다',
  '...',
  '단순',
  'sm',
  '상업',
  '영화',
  '라고',
  '생각',
  '하기엔',
  '...',
  '두',
  '사람',
  '의',
  '춤',
  '이',
  '너무',
  '인상',
  '적',
  '이다',
  '...',
  '</s>'],
 ['<s>',
  '이',
  '거',
  '평점',
  '보',
  '니까',
  '알바',
  '고',
  '용하는데',
  '제작비',
  '보다',
  '많이',
  '들어갔겠어요',
  '정말',
  '재미',
  '라고는',
  '찾아볼',
  '수',
  '없고',
  '특히',
  '마지막',
  '에',
  '여자애',
  '가',
  '경상도',
  '사람',
  '이',
  '들으면',
  '코웃음',
  '칠',
  '만큼',
  '어색한',
  '사투리',
  '로',
  '엄마',
  '한테',
  '말',
  '할',
  '때',
  '는',
  '그나마',
  '잡히던',
  '감정',
  '도',
  '깨져',
  '버렸습니다',
  '</s>'],
 ['<s>', 'TV', '시리즈', '중', '에는', '단연', '최고', '乃', '</s>'],
 ['<s>', '글쌔', '....', '슬프지만', '너무', '짜여진듯', '한', '</s>'],
 ['<s>', '여기', '서', '땡', '칠이', '얘', '낳지', '안나', '?', '</s>'],
 ['<s>', '너무', '재밌음', 'ㅠㅠ', '뭐랄까', '굉장히', '따뜻한', '느낌', '?', '</s>'],
 ['<s>', '견자단', '나오는', '영화', '중', '에', '제일', '노잼', '</s>'],
 ['<s>',
  '재밌기',
  '만한데',
  ';;',
  '왜',
  '이렇게',
  '욕',
  '을',
  '하',
  '셍',
  '휴',
  'ㅠㅠ',
  '</s>'],
 ['<s>',
  '실제',
  '사실',
  '은',
  '어땠는지',
  '모르겠으나',
  '의',
  '로운',
  '협객',
  '으로서',
  '김두한',
  '이',
  '거지',
  '패',
  '에서',
  '종로',
  '최고',
  '의',
  '주먹',
  '으로',
  '평정하는',
  '초기',
  '모습',
  '을',
  '잘',
  '보여',
  '줌',
  '.',
  '배경음악',
  '이',
  '영상',
  '과',
  '잘',
  '어울린다는',
  '느낌',
  '.',
  '참고',
  '로',
  '황정민',
  '이',
  '우미관',
  '지배인',
  '으로',
  '나와서',
  '유명하기도',
  '한',
  '영화',
  '.',
  '</s>'],
 ['<s>',
  '재밌는데',
  '?',
  '자막',
  '읽기',
  '힘들었지만',
  '영어권',
  '사람',
  '들',
  '이',
  '보면',
  '더',
  '몰입',
  '될듯',
  '공간',
  '이',
  '한정',
  '되있지만',
  '상상',
  '만으로도',
  '충분히',
  '재미나',
  '고',
  '생각',
  '할게',
  '많은',
  '영화',
  '바이러스',
  '가',
  '언어',
  '라는',
  '게',
  '참신한듯',
  '바',
  '이러수를',
  '소문',
  '괴담',
  '선동',
  '찌라시',
  '언론플레이',
  '등',
  '과',
  '대입',
  '해서',
  '생각',
  '해보면',
  '재밌을듯',
  '</s>'],
 ['<s>', '괜찮아요', '~', '</s>'],
 ['<s>', '내', '가', '극', '장가', '서', '본', '영화', '중', '제일', '쓰레기', '같았다', '</s>'],
 ['<s>', '.', '</s>'],
 ['<s>',
  '피는',
  '물',
  '보다',
  '진하다',
  '.',
  '이',
  '한마디',
  '로',
  '모든',
  '게',
  '표현',
  '되는',
  '영화',
  '.',
  '</s>'],
 ['<s>', '이뿌고', '따뜻한', '애니', '였어요', '</s>'],
 ['<s>', '너무', '좋았음', '</s>'],
 ['<s>', '어렷을때', '보고', '박준형', '에', '배신', '감', '을', 'ㅋㅋㅋㅋ', '</s>'],
 ['<s>', '차인표', '말투', '적응', '안', '돼', ',', '송선미', '이쁘다', '</s>'],
 ['<s>', '과소', '평가', '!', '확실히', '재밌고', '유쾌함', '</s>'],
 ['<s>',
  '훌륭한',
  '작가',
  '와',
  '뛰어난',
  '연',
  '출진',
  '이',
  '만나',
  ',',
  '훌륭하고',
  '뛰어난',
  '한',
  '편의',
  '드라마',
  '가',
  '만들어졌다',
  '.',
  '</s>'],
 ['<s>',
  '신선한',
  '소재',
  '로',
  '식상한',
  '영화',
  '를',
  '만들었어',
  '..',
  '유치한건',
  '둘째',
  '치고',
  '재밋게',
  '라도',
  '만들던가',
  '..',
  '</s>'],
 ['<s>',
  '다시',
  '봐도',
  '정말',
  '최고',
  '군',
  '요',
  '잭',
  '바우어',
  '형님',
  '이',
  '여기',
  '나왔었다니',
  '처음',
  '볼땐',
  '못',
  '느꼈던',
  '또',
  '하나',
  '의',
  '재미',
  '</s>'],
 ['<s>', '이런', '쓰레기', '영화', '좀', '만들지마라', '진짜', '재미없다', 'ㅡㅡ', '</s>'],
 ['<s>',
  '정말',
  '가슴',
  '아픈',
  '영화',
  '....',
  '질리지도',
  '않는',
  '영화',
  '....',
  '몇번',
  '을',
  '봐도',
  '...',
  '음악',
  '도',
  '너무',
  '좋아요',
  '...',
  'OST',
  '도',
  '구해',
  '들었다는',
  '...',
  '</s>'],
 ['<s>',
  '영화',
  '도',
  '못',
  '만들었지만',
  '이건',
  '탄생',
  '하지',
  '말았어야',
  '할',
  '그',
  '자체',
  '로',
  '쓰레기',
  '임',
  '..',
  '</s>'],
 ['<s>',
  '정말',
  '재밋어',
  '요',
  '...',
  '다',
  '들',
  '연기',
  '도',
  '잘',
  '하고',
  '볼',
  '만해',
  '요',
  '...~~~',
  '</s>'],
 ['<s>', '신기록', '갱신', '인가', '..', '간닷', '</s>'],
 ['<s>',
  '오시',
  '이',
  '마모루',
  '는',
  '영화',
  '를',
  '통해',
  '책',
  '을',
  '넘어서려',
  '한다',
  '.',
  '</s>'],
 ['<s>',
  '데어데블',
  '보다',
  '못',
  '한',
  '졸작',
  '.',
  'CG',
  '는',
  '훌륭하지만',
  '악마',
  '인형',
  '탈',
  '쓰고',
  '나오는게',
  '웃기',
  '고',
  '인물',
  '관계',
  '나',
  '스토리',
  '가',
  '너무',
  '뻔함',
  '.',
  '시간',
  '이',
  '아까',
  '움',
  '.',
  '짧은',
  '러닝',
  '타임',
  '이',
  '고마울',
  '정도',
  '.',
  '</s>'],
 ['<s>',
  '마트',
  '라는',
  '폐쇄된',
  '공간',
  '속',
  '에서',
  '그',
  '안',
  '에',
  '갇힌',
  '사람',
  '들',
  '의',
  '심리',
  '변화',
  '가',
  '인상',
  '적이네요',
  '.',
  '결말',
  '이',
  '인상',
  '적',
  '입니다',
  '.',
  '</s>'],
 ['<s>',
  '차인표',
  '연기',
  '는',
  '너무',
  '현',
  '실적',
  '이',
  '여서',
  '마음',
  '에',
  '와',
  '닿는다',
  '왕초',
  '드라마',
  '를',
  '볼때',
  '도',
  '난',
  '연기',
  '를',
  '하는',
  '건지',
  '진짜',
  '실제',
  '로',
  '그러는',
  '건지',
  '몰랐다',
  '이영화',
  '내용',
  '이',
  '쥐어',
  '짜는',
  '스토리',
  '지만',
  '차인표',
  '라는',
  '배우',
  '때문',
  '에',
  '영화',
  '가',
  '살았다',
  '너무',
  '현실',
  '적',
  '인',
  '연기력',
  '이다',
  '대단하다',
  '눈물',
  '한',
  '방울',
  '흘리지',
  '않았지만',
  '마음',
  '이',
  '아팠다',
  '</s>'],
 ['<s>',
  '이',
  '게',
  '뭐',
  '야',
  '엉',
  '엉',
  '본',
  '시리즈',
  '말고',
  '그냥',
  '나왔다면',
  '이',
  '정도',
  '는',
  '안',
  '줬겠지만',
  '본이라는',
  '이름',
  '을',
  '달',
  '고',
  '왔으니',
  '엉엉',
  '</s>'],
 ['<s>', '스토리', '가', '신선하다', '.', '재미있다', '.', '좋다', '.', '</s>'],
 ['<s>', '재밌었다', '.', '진저', '너무', '무', '서버', '~', 'ㅠ', '</s>'],
 ['<s>',
  '아직',
  '까지',
  '잊지',
  '못',
  '하는',
  '영화',
  '.',
  '제목',
  '부터',
  '마음',
  '에',
  '잔잔하게',
  '와',
  '닿는다',
  '.',
  '영화',
  '장면',
  '중',
  '에',
  '소',
  '낙비',
  '를',
  '피해',
  '놀라',
  '달려',
  '가는',
  '부분',
  '은',
  '정말',
  '☆',
  '어느',
  '멋진날',
  '~',
  '☆',
  '햇살',
  '비춰진',
  '행복한',
  '빗속',
  '을',
  '달리듯',
  '느껴졌었다',
  '</s>'],
 ['<s>',
  '지루하지',
  '않고',
  '가볍게',
  '볼수있는',
  '코믹',
  '스릴러',
  '영화',
  '네',
  '요',
  '저',
  '는',
  '잔인하고',
  '무거운',
  '스릴러',
  '영화',
  '보다',
  '오히려',
  '좋았습니다',
  '</s>'],
 ['<s>', '김민', '이', '너무', '어설픔', '졸작', '</s>'],
 ['<s>', '화면', '어지럽고', '엉', '성함', '과', '지루함', '의', '연속', '임', '.', '</s>'],
 ['<s>', '영화', '다', '보고', '평점', '읽는것이', '이영화', '최고', '의', '재미', 'ㅋ', '</s>'],
 ['<s>', '정말', '재밌게', '잘', '봤습니다', '!', '</s>'],
 ['<s>', '예수', '쟁이', '들', '좀', '제발', '인터넷', '에서', '안', '봤으면', '...', '</s>'],
 ['<s>',
  '작가',
  '의',
  '예리함과',
  '필',
  '력',
  '에',
  '박수',
  '를',
  '보냅니다',
  '.',
  '진보',
  '한',
  '드라마',
  '란',
  '바로',
  '이런',
  '것',
  '시청률',
  '의식',
  '하지',
  '마시고',
  '앞',
  '으로도',
  '좋은',
  '내용',
  '부탁드립니다',
  '</s>'],
 ['<s>',
  '작품',
  '성',
  '을',
  '떠나서',
  '보고',
  '나면',
  '너무',
  '너무',
  '찝찝해',
  '지는',
  '영화',
  '..',
  '</s>'],
 ['<s>',
  '초',
  '중학생',
  '수준',
  '의',
  '단조로운',
  '대사',
  '와',
  '지루하고',
  '재미',
  '없는',
  '영화',
  '.',
  '</s>'],
 ['<s>',
  '2012년',
  '도에',
  '참으로',
  '억지스럽네',
  '미국',
  '을',
  '욕',
  '해라',
  '뭐',
  '이런',
  '건가',
  '?',
  'ㅋㅋ',
  '</s>'],
 ['<s>',
  '1',
  '편이',
  '오억만배',
  '재밌는',
  '영화',
  '2',
  '편도',
  '나름',
  '대로는',
  '재밌지만',
  '...',
  '</s>'],
 ['<s>',
  '다시',
  '봐도',
  '수작',
  '이다',
  '.',
  '미국',
  '국수',
  '주의',
  '라',
  '뭐라는',
  '시점',
  '도',
  '있겠으나',
  '전쟁',
  '물',
  '중',
  '에',
  '손가락',
  '안',
  '에',
  '꼽',
  '을',
  '정도',
  '로',
  '잘',
  '만들어',
  '졌다',
  '.',
  '스토리',
  '라인',
  '은',
  '뻔하나',
  '그',
  '뻔한',
  '걸',
  '너무',
  '잘',
  '살렸다',
  '.',
  '언제',
  '봐도',
  '다시',
  '봐도',
  '재미',
  '있다',
  '.',
  '10년',
  '이',
  '지난',
  '영화',
  '가',
  '..',
  '</s>'],
 ['<s>',
  '클럽',
  '과',
  '사건',
  '의',
  '연결',
  '이',
  '전혀',
  '안된다',
  '.',
  '섹스',
  '클럽',
  '얘기',
  '는',
  '흥미',
  '거리',
  '일',
  '뿐',
  '스토리',
  '연관',
  '이',
  '없다',
  '.',
  '</s>'],
 ['<s>', '다니엘', ',,', '미쉘', '페이퍼', ',,', '마틴', '스콜', '세지', '~~', '쵝오', '</s>'],
 ['<s>',
  '탕웨이',
  '..',
  '이제껏',
  '관심',

In [63]:
unigram = Counter(w for token in tokens for w in token)
bigram = Counter((token[i], token[i+1])for token in tokens for i in range(len(token) - 1))

In [64]:
print(len(unigram))
print(len(bigram))

13800
51067

In [65]:
new_texts = [
    '이 영화 좋네',
    '시간이 가는줄 몰랐다',
    '아 이런 내 시간',
    '연기가 그닥 ... 배우 ...'
]

In [66]:
result = []
for text in new_texts:
    tokens = tokenize(text)
    # 로그확률
    lp = log_prob(tokens)
    # 혼란도
    perple = perplexity(tokens)
    result.append([text, lp, perple])

In [59]:
pd.DataFrame(result, columns= ['문장', '로그확률', '혼란도'])

                  문장       로그확률        혼란도
0            이 영화 좋네 -16.215184  57.615751
1        시간이 가는줄 몰랐다 -19.778073  52.227788
2          아 이런 내 시간 -22.959637  98.684443
3  연기가 그닥 ... 배우 ... -27.348719  49.747484